CREATE DATABASE message_gateway;
CREATE USER mgw WITH ENCRYPTED PASSWORD 'mgw_pwd';
GRANT ALL PRIVILEGES ON DATABASE message_gateway TO mgw;
GRANT USAGE, CREATE ON SCHEMA public TO mgw;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mgw;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO mgw;

CREATE DATABASE content_system;
CREATE USER cms WITH ENCRYPTED PASSWORD 'cms_pwd';
GRANT ALL PRIVILEGES ON DATABASE content_system TO cms;
GRANT USAGE, CREATE ON SCHEMA public TO cms;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cms;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO cms;
